### ISSUE TITLE
No support for strands

### ISSUE THREAD

**Issue by yhoogstrate** [konstantint/intervaltree-bio#1]
Dear @konstantint ,

In certain cases it may be desired to distinguish between `chr:100-200(+)` and `chr:100-200(-)`. An additional object (e.g. GenomeIntervalTreeStranded) taking this into account would be helpful to me. If you're interested I may be able to help implementing.

all best,

Youri

**Comment by konstantint** [comment]
How would you envision this additional support? Do you mean simply an overload to the search method which would filter the results to only include intervals with a given strand? If so, it might be easier for you to write a custom method of your own outside of the library, e.g.:

```
def search_stranded(tree, from, to, strand):
    return [intv for intv in tree.search(from, to) if (intv.data['strand'] == strand)]
```

I am not immediately convinced adding a one-liner like that to the library is very necessary - after all other people might want to filter on other attributes as well hence the question becomes "maybe we should add a method like that:"

```
 def search_filtered(tree, from, to, predicate):
     return filter(predicate, tree.search(from, to))
```

To me this method does not seem to add much to its raw form. The invocation "search_filtered(....)" may even contain more characters than "filter( .... )".
