### ISSUE TITLE
Please use release tags

### ISSUE THREAD

**Issue by tillea** [konstantint/intervaltree-bio#5]
Hi,
intervaltree-bio is packaged for Debian.  It would be helpful if you would use tags for your releases to enable us detecting new releases automatically to guarantee that we can provide up to date code to our users.
Kind regards, Andreas.

**Comment by konstantint** [comment]
OK. Is there a specific tag format you expect?

**Comment by tillea** [comment]
On Thu, Jan 12, 2017 at 04:53:11AM -0800, Konstantin Tretyakov wrote:
> OK. Is there a specific tag format you expect?

We have currently packaged version 1.0.1 in Debian.  Just use this
format (or any later version if you might have a new release.

Thanks for your quick response

      Andreas.

-- 
http://fam-tille.de

**Comment by tillea** [comment]
Do you need further help to add a release tag?  Its just a

    git tag 1.0.1
    git push --tags

away (or whatever version you want to tag)

**Comment by konstantint** [comment]
Yes, sorry for the delay. I was hoping to do all the tag-adding together with some meaningful next change, but so far none of those have been in the working.
