### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jasper1918** [konstantint/intervaltree-bio#6]
@konstantint - I use this package internally to several projects I am working on and find it rather convenient. Can you push a new pypi release with the current state to help with deployment? By chance if you are interested, I could take on a maintainer role to help facilitate.

**Comment by konstantint** [comment]
I believe the current version is in PyPI, correct me if I'm wrong. There were no changes here for quite a long time. If you have something to contribute - please do. I'll gladly add you as a maintainer.
